version: "3"
services:
  django-test:
    container_name: django-test
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: .
    user: "${UID}"
    volumes:
      - ./:/app
    ports:
      - 9000:8000
