version: "3"
services:
  django-test:
    container_name: django-test
    command: bash
    tty: true
    build:
      context: .
      args:
        ENV_TYPE: dev
        UID: 1000
    user: "1000"
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 9000:8000
