version: "3"
services:
  django-test:
    container_name: django-test
    command: bash
    tty: true
    build:
      context: .
      args:
        ENV_TYPE: dev
    user: "${UID}"
    volumes:
      - ./:/app
    ports:
      - 9000:8000
